# Generated by Django 6.0.2 on 2026-04-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question_12', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
