# Generated by Django 6.0.2 on 2026-04-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question_13', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='confirm_password',
        ),
    ]
