# Generated by Django 6.0.2 on 2026-04-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question_14', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='specialization',
            field=models.CharField(default='', max_length=100),
        ),
    ]
