# Generated by Django 6.0.2 on 2026-04-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question_14', '0002_doctor_profile_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
