# Generated by Django 6.0.2 on 2026-04-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question_14', '0003_alter_doctor_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_profile',
            name='email',
        ),
    ]
