# Generated by Django 6.0.2 on 2026-04-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question_7', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='hospital',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='qualification',
            field=models.CharField(max_length=40),
        ),
    ]
