# Generated by Django 6.0.2 on 2026-04-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
