# Generated by Django 6.0.2 on 2026-04-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctorrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=40)),
                ('experience', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
            ],
        ),
    ]
